---
directories:
    root: ../
    element_files: elements/
    element_objects: build/elements/

window:
    width: 1024
    height: 1024

    near: 1.0
    far: 80.0

    children:
        -   id: camera
            type: camera
            speed_factor: 3.0
            children:
                -   id: skybox
                    type: skybox
                -   id: terrain
                    type: terrain
                    terrain: fft-terrain.tga
                    texture: grass.tga
                    scale: 8
                -   id: screen
                    type: screen
